### ISSUE TITLE
error with mycobank

### ISSUE THREAD

**Issue by lauraDRH** [ropensci/taxizesoap#21]
Hi! I am trying to search a species with search_mycobank but I keep getting this error:
  _Extra content at the end of the document
  Error: 1: StartTag: invalid element name
  2: Extra content at the end of the document_

I am just using the code from the example: 
  _>library('taxizesoap')
  >myco_search(filter='Name CONTAINS "Candida boidinii"')
  StartTag: invalid element name
  Extra content at the end of the document
  Error: 1: StartTag: invalid element name
  2: Extra content at the end of the document_

Thanks!

**Comment by sckott** [comment]
The query we have for Mycobank is no longer working as they've changed something on their end. I'm going to mark this package as archived since most functionality has moved to `taxize` and it's too difficult to maintain code that works with SOAP web services in R. 

As far as I can tell Mycobank no longer has a web service, so you'd have to query from their website
